// Package interfaces is to define all interface methods for each model type
// Author : readyGo "JitenP@Outlook.Com"
// This code is generated by readyGo. You are free to make amendments as and where required
package interfaces

import (
	"github.com/jitenpalaparthi/bodylog/models"
)

// BodyLogInterface is to define all bodyLog related methods
type BodyLogInterface interface {
	CreateBodyLog(bodyLog *models.BodyLog) (string, error)
	// UpdateCovidDataByID(id string, data map[string]interface{}) (string, error)
	// DeleteCovidDataByID(id string) (string, error)
	// GetCovidDataByID(id string) (*models.BodyLog, error)
	// GetAllCovidDatas(skip int64, limit int64, selector interface{}) ([]models.BodyLog, error)
	// GetAllCovidDatasBy(key string, value interface{}, skip int64, limit int64) ([]models.BodyLog, error)
	// Write any additional methods and implement them in database package
}
